server:
  port: 8080

shortener:
  approach: "hash" # "hash" or "random"
  hashing_algorithm: "sha256" # "md5", "sha256", "fnv", "murmur", "xxhash"
  max_char_limit: 6

database:
  host: "127.0.0.1"
  port: 5432
  user: "your_database_username"
  password: "your_database_password"
  name: "url_shortner_app"
